### ISSUE TITLE
Issue deploying instance

### ISSUE THREAD

**Issue by galeee** [TheMisinformationGame/MisinformationGame#30]
Whenever I try to run ./deploy.sh in my VS Code terminal, it successfully installs all the dependencies and everything, but once it actually gets to the "Deploying the application to Firebase..." stage, it returns this error message:

> There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.
> 
> Error: HTTP Error: 403, Read access to project '[project title]' was denied: please check billing account associated and retry
> Deploying to Firebase failed!

Would really appreciate some help with this. Thanks! 😊

**Comment by Sothatsit** [comment]
Hi there, I'm sorry to hear you're having troubles deploying the Misinformation Game! It seems that you have encountered a permissions issue. This likely means the Google account you signed into is locked out of accessing your Firebase project. Here are some potential fixes:

1. **Billing account verification:**
        It is possible that there is an issue with your billing account, in which case Google may lock you out. To check this, sign into the [Google Cloud Console Billing Section](https://console.cloud.google.com/billing). If you have no billing account, then it should say something similar to "Billing is disabled", in which case this is probably not the problem you are facing. Otherwise, make sure your billing account is active and linked to your Firebase project. If it's not linked, or there's a billing issue (expired credit card, overdue invoice, etc.), then once you resolve that the deploy script should hopefully work.

2. **Double-check you are using the correct account:**
        Try re-run the deploy script and make sure you signed in to the correct Firebase account when you were prompted by the deploy script.

3. **Check account permissions:**
        If you are not using the admin account to deploy, then you may need to grant your own Google account some permissions. I'm not sure about the process required to grant those permissions, but just using the admin account that was used to create the Firebase project would likely be easier if possible.

4. **Contact Google support:**
        If you've tried all the fixes above and the issue persists, it might be a good idea to contact Google Cloud or Firebase support with the error.

Hope this helps! Let me know if you manage to get it working.

Thanks,
~ Paddy L.

**Comment by galeee** [comment]
> Hi there, I'm sorry to hear you're having troubles deploying the Misinformation Game! It seems that you have encountered a permissions issue. This likely means the Google account you signed into is locked out of accessing your Firebase project. Here are some potential fixes:
> 
> 1. **Billing account verification:**
>    It is possible that there is an issue with your billing account, in which case Google may lock you out. To check this, sign into the [Google Cloud Console Billing Section](https://console.cloud.google.com/billing). If you have no billing account, then it should say something similar to "Billing is disabled", in which case this is probably not the problem you are facing. Otherwise, make sure your billing account is active and linked to your Firebase project. If it's not linked, or there's a billing issue (expired credit card, overdue invoice, etc.), then once you resolve that the deploy script should hopefully work.
> 2. **Double-check you are using the correct account:**
>    Try re-run the deploy script and make sure you signed in to the correct Firebase account when you were prompted by the deploy script.
> 3. **Check account permissions:**
>    If you are not using the admin account to deploy, then you may need to grant your own Google account some permissions. I'm not sure about the process required to grant those permissions, but just using the admin account that was used to create the Firebase project would likely be easier if possible.
> 4. **Contact Google support:**
>    If you've tried all the fixes above and the issue persists, it might be a good idea to contact Google Cloud or Firebase support with the error.
> 
> Hope this helps! Let me know if you manage to get it working.
> 
> Thanks, ~ Paddy L.

Thank you for your help! So, it only deployed successfully after I linked a billing account and set it to the Blaze plan. It doesn't deploy if I'm on the Spark plan. Forgive me if I'm mistaken, but I thought the MIsinformation Game is deployable with the free plan? I don't want to accidentally be charged for going over any limits haha. 😅

**Comment by Sothatsit** [comment]
> > Hi there, I'm sorry to hear you're having troubles deploying the Misinformation Game! It seems that you have encountered a permissions issue. This likely means the Google account you signed into is locked out of accessing your Firebase project. Here are some potential fixes:
> > 
> > 1. **Billing account verification:**
> >    It is possible that there is an issue with your billing account, in which case Google may lock you out. To check this, sign into the [Google Cloud Console Billing Section](https://console.cloud.google.com/billing). If you have no billing account, then it should say something similar to "Billing is disabled", in which case this is probably not the problem you are facing. Otherwise, make sure your billing account is active and linked to your Firebase project. If it's not linked, or there's a billing issue (expired credit card, overdue invoice, etc.), then once you resolve that the deploy script should hopefully work.
> > 2. **Double-check you are using the correct account:**
> >    Try re-run the deploy script and make sure you signed in to the correct Firebase account when you were prompted by the deploy script.
> > 3. **Check account permissions:**
> >    If you are not using the admin account to deploy, then you may need to grant your own Google account some permissions. I'm not sure about the process required to grant those permissions, but just using the admin account that was used to create the Firebase project would likely be easier if possible.
> > 4. **Contact Google support:**
> >    If you've tried all the fixes above and the issue persists, it might be a good idea to contact Google Cloud or Firebase support with the error.
> > 
> > Hope this helps! Let me know if you manage to get it working.
> > Thanks, ~ Paddy L.
> 
> Thank you for your help! So, it only deployed successfully after I linked a billing account and set it to the Blaze plan. It doesn't deploy if I'm on the Spark plan. Forgive me if I'm mistaken, but I thought the MIsinformation Game is deployable with the free plan? I don't want to accidentally be charged for going over any limits haha. sweat_smile

Hi galeee, it should be possible to deploy the Misinformation Game under a free plan... It is concerning that you were not able to! I have deployed several free instances in the past. I hope this was just a once-off issue.

Are you able to now downgrade to the Spark plan after you have successfully deployed? There should be a button to "Modify" your subscription in the bottom left of your Firebase console page.
![downgrade-to-spark-plan](https://github.com/TheMisinformationGame/MisinformationGame/assets/1185881/4deb17e3-110b-4776-b9ec-032907851281)

That way they won't charge you if you hit the free limits! I'm glad to hear that you've gotten it working though.

All the best,
~ Paddy L.

**Comment by galeee** [comment]
> > > Hi there, I'm sorry to hear you're having troubles deploying the Misinformation Game! It seems that you have encountered a permissions issue. This likely means the Google account you signed into is locked out of accessing your Firebase project. Here are some potential fixes:
> > > 
> > > 1. **Billing account verification:**
> > >    It is possible that there is an issue with your billing account, in which case Google may lock you out. To check this, sign into the [Google Cloud Console Billing Section](https://console.cloud.google.com/billing). If you have no billing account, then it should say something similar to "Billing is disabled", in which case this is probably not the problem you are facing. Otherwise, make sure your billing account is active and linked to your Firebase project. If it's not linked, or there's a billing issue (expired credit card, overdue invoice, etc.), then once you resolve that the deploy script should hopefully work.
> > > 2. **Double-check you are using the correct account:**
> > >    Try re-run the deploy script and make sure you signed in to the correct Firebase account when you were prompted by the deploy script.
> > > 3. **Check account permissions:**
> > >    If you are not using the admin account to deploy, then you may need to grant your own Google account some permissions. I'm not sure about the process required to grant those permissions, but just using the admin account that was used to create the Firebase project would likely be easier if possible.
> > > 4. **Contact Google support:**
> > >    If you've tried all the fixes above and the issue persists, it might be a good idea to contact Google Cloud or Firebase support with the error.
> > > 
> > > Hope this helps! Let me know if you manage to get it working.
> > > Thanks, ~ Paddy L.
> > 
> > 
> > Thank you for your help! So, it only deployed successfully after I linked a billing account and set it to the Blaze plan. It doesn't deploy if I'm on the Spark plan. Forgive me if I'm mistaken, but I thought the MIsinformation Game is deployable with the free plan? I don't want to accidentally be charged for going over any limits haha. sweat_smile
> 
> Hi galeee, it should be possible to deploy the Misinformation Game under a free plan... It is concerning that you were not able to! I have deployed several free instances in the past. I hope this was just a once-off issue.
> 
> Are you able to now downgrade to the Spark plan after you have successfully deployed? There should be a button to "Modify" your subscription in the bottom left of your Firebase console page. ![downgrade-to-spark-plan](https://user-images.githubusercontent.com/1185881/258959802-4deb17e3-110b-4776-b9ec-032907851281.png)
> 
> That way they won't charge you if you hit the free limits! I'm glad to hear that you've gotten it working though.
> 
> All the best, ~ Paddy L.

hello paddy! yes, i can switch back to spark after deploying. the only downside is that i have to switch back to blaze whenever i want to make new changes to the feed but other than that it works well. not sure why it didn't let me deploy using the spark plan in the first place, but nevertheless thank you so much for your help! 😊
