### ISSUE TITLE
Non-Technical Installation Error

### ISSUE THREAD

**Issue by BrettlandC** [TheMisinformationGame/MisinformationGame#32]
When following the non-technical installation guide, I came upon the error "Bash: ./deploy.sh: No such file or directory". I am unsure what file this is supposed to be to insure I have it downloaded. I successfully downloaded all software with proper verifications and copied over the necessary firebase-config.js data. Any help would be appreciated!

**Comment by Sothatsit** [comment]
> When following the non-technical installation guide, I came upon the error "Bash: ./deploy.sh: No such file or directory". I am unsure what file this is supposed to be to insure I have it downloaded. I successfully downloaded all software with proper verifications and copied over the necessary firebase-config.js data. Any help would be appreciated!

Hi there, it seems like your Bash terminal has the wrong working directory. That means it is looking in the wrong place when trying to find the `./deploy.sh` script. You should be able to fix this by typing `cd <path to your installation>`. For example, if you downloaded the codebase into `/Users/abc/Documents/MisinformationGame`, you'd type `cd /Users/abc/Documents/MisinformationGame`. On most computers, you can also drag the folder from a file-system explorer (e.g., Finder or File Explorer) into your terminal, and it will automatically fill in the path to your codebase. Good luck, I hope this helps!

**Comment by BrettlandC** [comment]
Thank you so much for the comment! I was able to update the working directory and run the document. However, I have run into another issue :(. The terminal states that it was unable to install google cloud, which is what I assume prevented it from asking me to sign into firebase or any of the following steps listed in the guide. I'd greatly appreciate any extra help if possible!

**Comment by Sothatsit** [comment]
Hi, could you copy and paste the error that was given when it said it couldn't install Google Cloud? I would normally expect there to be other messages about why it couldn't be installed.

Otherwise, it could be a permissions issue, which are a bit more difficult to resolve!

**Comment by BrettlandC** [comment]
Of course!

Here is everything: 
$ .GoogleCloud/google-cloud-sdk/install.sh
Welcome to the Google Cloud CLI!
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Sothatsit** [comment]
Hi, it seems that you don't have Python installed. I saw that you mentioned that you tried turning Python off in your previous message though, so could you try with it turned back on? Otherwise, installing Python could be the solution!

**Comment by BrettlandC** [comment]
Interestingly, I actually tried that as well! I downloaded python, but it continues to give the same error

**Comment by Sothatsit** [comment]
Ahh, I see. It seems that this is a bit of a more difficult problem than I'd hoped! I was having a look at the error on StackOverflow, and it seems that some people have found different solutions to it there: https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store

Although, I get the impression that you have tried some of these things based upon you looking at Manage App Execution Aliases.

Running the terminal in Visual Studio Code was supposed to work around some of these issues. Are you using the terminal within VSCode, or a different one?

**Comment by BrettlandC** [comment]
I am using the terminal in VS code with git-bash, like section 5.2 and 5.3 say to do. I will look through that link nd see if I can find any other solutions potentially. If not, would a full delete/re-download be useful?

**Comment by Sothatsit** [comment]
Thanks for confirming that, and thanks for working to figure this problem out! If you could let me know how the advice from the link works for you, we can put a note into the installation guide for future users, which would be great.

A full delete/re-download would probably not help in this case, since the problem is that the script can't find a Python installation. Based upon the error you gave though, maybe you could try just typing `python` into the terminal, to see if the Microsoft Store is able to install it.

**Comment by BrettlandC** [comment]
Hi!

I wanted to come back and update that using the "python" command in the terminal and downloading python directly from Microsoft Store actually solved the problem! The only thing I would mention is that the guide does not mention setting up a google cloud account yourself, logging in, and assigning that billings account to your firebase. This caused me some brief issues and might be good to mention in the guide for future users. 

Your help was so useful, thank you!

**Comment by Sothatsit** [comment]
> Hi!
> 
> I wanted to come back and update that using the "python" command in the terminal and downloading python directly from Microsoft Store actually solved the problem! The only thing I would mention is that the guide does not mention setting up a google cloud account yourself, logging in, and assigning that billings account to your firebase. This caused me some brief issues and might be good to mention in the guide for future users.
> 
> Your help was so useful, thank you!

It is great to hear that you were able to get things set up! The billing issue is something we will look into. It isn't required for everyone (and hasn't been for us), so it has caught a few people off guard. Good luck with your studies!
